HOST: "0.0.0.0"

# 0: off, 1: on
SSL_SWITCH: 1
SSL_CA: "cert/ca.crt"
SSL_KEY: "cert/node.key"
SSL_CRT: "cert/node.crt"

# 0801配置
NODE_TO_PARTNER_RPC_PORT: 43454
PARTNER_TO_NODE_RPC_PORT: 43451

NODE_ENDPOINT: "127.0.0.1:43472"

AGENCY_LIST:
  #- "SG: [@IDC_PPCS_SG_MODEL_GATEWAY_ENDPOINT]"
  - "WeBank: 127.0.0.1:43451"

MAX_MESSAGE_LENGTH_MB: 100
