HTTP_HOST: "0.0.0.0"
HTTP_PORT: 43471
HTTP_THREAD_NUM: 8

JOB_TIMEOUT_H: 1800
WORKSPACE: "/data/app/files/job"
STORAGE_TYPE: "HDFS"
HDFS_URL: "http://127.0.0.1:50070"

# mysql or dm
DB_TYPE: "mysql"
SQLALCHEMY_DATABASE_URI: "mysql://[*user_ppcsmodeladm]:[*pass_ppcsmodeladm]@[@4346-TDSQL_VIP]:[@4346-TDSQL_PORT]/ppcsmodeladm?autocommit=true&charset=utf8mb4"
# SQLALCHEMY_DATABASE_URI: "dm+dmPython://ppcv16:ppc12345678@127.0.0.1:5236"
